name: shadowsocks-android

on:
  push:
    tags:
      - 'android*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'shadowsocks/shadowsocks-android'
        ref: ${{ github.ref }}
        submodules: 'true'

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        
    - name: Rust with Android targets installed
      run: |
        cd core/src/main/rust/shadowsocks-rust
        rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
      
    - name: Build
      run: ./gradlew assembleRelease
        
    #- name: Upload
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: shadowsocks-rust
    #    path: build/release/

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: build/release/*
        tag: ${{ github.ref }}
        file_glob: true
