name: shadowsocks-rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: "-C strip=symbols"
    strategy:
      matrix:
        target:
          #- i686-unknown-linux-musl
          #- x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl
          #- arm-unknown-linux-gnueabi
          #- arm-unknown-linux-gnueabihf
          #- arm-unknown-linux-musleabi
          #- arm-unknown-linux-musleabihf
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- mips-unknown-linux-musl
          #- mips-unknown-linux-gnu
          - mipsel-unknown-linux-musl

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'shadowsocks/shadowsocks-rust'
        ref: ${{ github.ref }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: nightly
        default: true
        override: true
        
    - name: Install cross
      run: cargo install cross
      
    - name: Build ${{ matrix.target }}
      timeout-minutes: 120
      env:
        EXTRA_FEATURES: "stream-cipher aead-cipher-extra"
      run: |
          compile_target=${{ matrix.target }}
          if [[ "$compile_target" == "mips-"* || "$compile_target" == "mipsel-"* || "$compile_target" == "mips64-"* || "$compile_target" == "mips64el-"* ]]; then
            sudo apt-get update -y && sudo apt-get install -y upx;
            if [[ "$?" == "0" ]]; then
              compile_compress="-u"
            fi
          fi
          if [[ "$compile_target" == "aarch64-"* ]]; then
            compile_features="$compile_features -f armv8 -f neon"
          fi

          cd build
          ./build-release -t ${{ matrix.target }} $compile_features $compile_compress
        
    #- name: Upload
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: shadowsocks-rust
    #    path: build/release/

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: build/release/*
        tag: ${{ github.ref }}
        file_glob: true
