name: SmartControl_Android_MQTT

on:
  push:
    tags:
      - 'mqtt*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'a2633063/SmartControl_Android_MQTT'

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
        
    
    - name: Build
      run: |
        sed -i 's/build:gradle:4.1.1/build:gradle:4.2.1/g' ./build.gradle
        sed -i 's/compileSdkVersion 28/compileSdkVersion 30/g;s/targetSdkVersion 28/targetSdkVersion 30/g;s/appcompat:appcompat:1.1.0/appcompat:appcompat:1.2.0/g;s/junit:junit:4.12/junit:junit:4.13.2/g;s/androidx.test.ext:junit:1.1.1/androidx.test.ext:junit:1.1.2/g;s/androidx.test.espresso:espresso-core:3.2.0/androidx.test.espresso:espresso-core:3.3.0/g' ./LineTable/build.gradle
        sed -i 's/compileSdkVersion 27/compileSdkVersion 30/g;s/targetSdkVersion 27/targetSdkVersion 30/g' ./esptouch/build.gradle
        sed -i 's/compileSdkVersion 28/compileSdkVersion 30/g;s/targetSdkVersion 28/targetSdkVersion 30/g;s/appcompat:appcompat:1.0.0/appcompat:appcompat:1.2.0/g;s/com.google.android.material:material:1.0.0/com.google.android.material:material:1.3.0/g;s/androidx.constraintlayout:constraintlayout:1.1.3/androidx.constraintlayout:constraintlayout:2.0.4/g;s/org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1/org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5/g' ./app/build.gradle

        chmod +x ./gradlew
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        rm $GITHUB_WORKSPACE/signing-key.jks
        
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./app/build/outputs/apk/release/*
        tag: ${{ github.ref }}
        file_glob: true
