name: SmartControl_Android_MQTT

on:
  push:
    tags:
      - 'mqtt*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'a2633063/SmartControl_Android_MQTT'

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
        
    
    - name: Build
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        rm $GITHUB_WORKSPACE/signing-key.jks
        
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./app/build/outputs/apk/release/*
        tag: ${{ github.ref }}
        file_glob: true
